# Generated by Django 4.1 on 2022-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcardimpression',
            options={},
        ),
        migrations.RemoveField(
            model_name='flashcardimpression',
            name='levelknown',
        ),
        migrations.RemoveField(
            model_name='flashcardimpression',
            name='leveltried',
        ),
        migrations.AddField(
            model_name='flashcardimpression',
            name='review',
            field=models.IntegerField(default=0),
        ),
    ]
