# Generated by Django 4.1 on 2022-10-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='YXTXEPHJ', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastTimestamp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.timestamp'),
        ),
    ]
