# Generated by Django 4.1 on 2022-11-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_day1_remove_profile_day2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePictue',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='DLEGLUWS', max_length=10),
        ),
    ]
