# Generated by Django 4.1 on 2022-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_profilepictue_alter_profile_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilePictue',
            new_name='profilePicture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='GWSRLNNZ', max_length=10),
        ),
    ]
