"""
Django settings for synctio project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

DATE_INPUT_FORMATS =('%m/%d/%Y')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL='/images/'
MEDIA_ROOT=BASE_DIR / "images"
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static')
]
#EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST_USER='adalangford123@gmail.com'
#EMAIL_HOST='smtp.gmail.com'
#EMAIL_PORT=587
#EMAIL_USE_TLS =True
#EMAIL_HOST_PASSWORD=""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@7tgtan(_r9363fyyx92e*^#t@8im-(z$z1@*y=%*s&%1a0dli'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


CSRF_TRUSTED_ORIGINS=["http://127.0.0.1:8000/",]

# Application definition
#AXES_FAILURE_LIMIT:6
#AXES_COOLOFF_TIME: 2
#AXES_RESET_ON_SUCCESS:True

#DEFENDER_LOCKOUT_TEMPLATE="accounts/lockout_template.html"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'flashcards.apps.FlashcardsConfig',
    'rest_framework',
    'django.contrib.sites',
    "openaiapi",
    "schedule",
   # 'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
  #  'defender',
  #  'axes',

]
#AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
 #   'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
  #  'allauth.account.auth_backends.AuthenticationBackend',
#]
#AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
  #  'axes.backends.AxesStandaloneBackend',

    # Django ModelBackend is the default authentication backend.
  #  'django.contrib.auth.backends.ModelBackend',
#]
#AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
   # 'axes.backends.AxesStandaloneBackend',

    # Django ModelBackend is the default authentication backend.
  #  'django.contrib.auth.backends.ModelBackend',
#]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  #  'defender.middleware.FailedLoginMiddleware',
 #   'axes.middleware.AxesMiddleware', # Axes
]

ROOT_URLCONF = 'synctio.urls'

SITE_ID=1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"/"synctio"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'synctio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default':{
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'synctioDB',
#         'USER': 'postgres',
#         'PASSWORD': 'p1o2s3t4g5r6e7s8!',
#         'HOST':'localhost',
#         'PORT': '5432'
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL="/login"
LOGIN_REDIRECT_URL="/"

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#email settings
EMAIL_HOST="localhost"
EMAIL_PORT='1025'
EMAIL_HOST_USER=''
EMAIL_HOST_PASSWORD=''
EMAIL_USE_TLS=False
