from django.urls import path, re_path
from . import views

urlpatterns = [
   path('home/', views.home, name="home"),
#    path('deck-api/', views.DeckApi.as_view(), name="deck-api"),
    #path('formview/', views.FlashcardFormView.as_view(), name="flashcard-view"),
   # path("flashcard-detail/<str:pk>/", views.flashcardDetail, name="flashcardDetail"),
  #  path("flashcard-update/<str:pk>/", views.flashcardUpdate, name="flashcardUpdate"),
 #   path("flashcard-delete/<str:pk>/", views.flashcardDelete, name="flashcardDelete"),
#    path("api-overview/", views.apiOverview, name="apiOverview"),
 #   path("flashcard-list/", views.FlashcardList, name="flashcardList"),
#    path("flashcard-create/", views.flashcardCreate, name="flashcardCreate"),
 #   path("deck/<str:pk>/", views.deckView, name="deck"),
   path('flashcard-create-view/', views.flashcardCreateView, name="flashcardCreateView"),
   path('deck-view/<str:pk>/', views.deckView, name="deck"),
 #   path('update-json-deck/<str:pk>/', views.deckView, name="deck"),
   path('update-json-flashcard/<str:pk>/', views.updateJsonFlashcard, name="updateJsonDeck"),
  #  path('flashcard-detail/<str:pk>/', views.FlashcardDetail.as_view(), name="flashcard-detail"),
   path('delete-json-flashcard/<str:pk>/', views.deleteJsonFlashcard, name="flashcard-detail"),
   path('flashcard-list/<str:pk>/', views.FlashcardList, name="flashcard-list"),
   #re_path('^flashcard-list/(?P<deck>.+)/$', views.FlashcardList.as_view(), name="flashcard-list"),
#   re_path('^deck-detail/(?P<pk>\d+)/$', views.DeckDetail.as_view(), name="flashcard-detail"),
   #path('deck-list/', views.DeckList.as_view()),
   #path('folder-detail/<str:pk>/', views.FolderDetail.as_view(), name="flashcard-detail"),
   #path('folder-list/', views.FolderList.as_view()),
   path('deck-json-update/<str:pk>/', views.updateJsonDeck, name="UpdateJsonDeck"),
   path('deck-detail/<str:pk>/', views.DeckDetail, name="deck-detail"),
   #path('create-deck/', views.createDeck, name="createDeck"),
   #path('create-flashcard/', views.createFlashcard, name="createFlashcard"),
   #path('update-deck/<str:pk>/', views.updateDeck, name="updateDeck"),
   path('delete-deck/<str:pk>/', views.deleteDeck, name="deleteDeck"),
   path('delete-folder/<str:pk>/', views.deleteFolder, name="deleteFolder"),
   path('flashcardplay/<str:pk>/', views.flashcardplayview, name="flashcardplay"),
    # path('flashcardplayapi/', views.flashcardfindapiview, name="flashcardplayapi"),
   path('flashcardwriteapi/<str:pk>/', views.flashcardwriteview, name="flashcardwriteapi"),
   path('deckCreateEmpty/', views.deckCreateEmpty, name="deckCreateEmpty"),
   path('folderCreateEmpty/', views.folderCreateEmpty, name="folderCreateEmpty"),
   path("windblowing/<str:pk>/", views.flashcardWordBlowing, name="windblowing"),
]