# Generated by Django 4.1 on 2022-10-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_minutes_timestamp_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
