# Generated by Django 4.1 on 2022-10-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_timestamp_user'),
        ('schedule', '0003_alter_timestamp_start'),
    ]

    operations = [
    ]
